### ISSUE TITLE
PDF Viewing doesn't work

### ISSUE THREAD

**Issue by Kokobe** [neevaco/neeva-android#1013]
**Describe the bug**
When trying to view a pdf (for example: https://kokobe.github.io/Jehan_Chang_Resume.pdf) it shows a blank screen: 

https://user-images.githubusercontent.com/20916043/193155370-04610fa8-3968-4725-bfd0-e87309333d25.mp4

**To Reproduce**
1. Go to any website to view a pdf. (If that doesn't work, try long pressing on a pdf link and opening it in a new tab)
3. See that there is no pdf view
4. You can download the pdf to confirm its not the pdf's fault.

**Expected behavior**
Maybe we should prompt with a dialog to download a pdf when opening up a pdf file via url? We should discuss any workarounds (if a workaround is needed). 

**Smartphone (please complete the following information):**
 - Device: Samsung
 - Android version: API 31

**Comment by dan-alcantara-neeva** [comment]
Does clicking on that link trigger a download?

**Comment by Kokobe** [comment]
Nope

**Comment by dan-alcantara-neeva** [comment]
Bumping up the priority here because people use PDFs for menus all the time.

**Comment by Kokobe** [comment]
TODO: look at weblayer shell and see if it's also broken
