### ISSUE TITLE
Users get signed out after upgrading to latest internal

### ISSUE THREAD

**Issue by dan-alcantara-neeva** [neevaco/neeva-android#1043]
https://github.com/neevaco/neeva-android/pull/1001 switched the browser's cookie jar as the source of truth.  However, the app used to take the login cookie from the `SharedPreferences` and then set it _temporarily_ as a session cookie in the browser cookie jar.  In this case, every time the app died, the cookie in the browser cookie jar would get deleted.  This is problematic after the upgrade because the browser's cookie jar won't have the login cookie, so sync the browser cookie to the SharedPreferences clears it.  Looking for workarounds...

**Comment by Kokobe** [comment]
Somehow when running the app, signing in, and then killing the app, I'm still signed in.

**Comment by dan-alcantara-neeva** [comment]
Yeah that's fine.  This only happens if you upgraded from an older version.
