### ISSUE TITLE
Downloads: No way to cancel a download (WebLayer issue)

### ISSUE THREAD

**Issue by Kokobe** [neevaco/neeva-android#1057]
**Describe the bug**
Can't cancel a download while something large is downloading. WebLayer might be missing that functionality in their interface. 

**To Reproduce**
1. Download something really large
2. See that you can't cancel this download. 

**Expected behavior**
Perhaps we can have something in the popup model to cancel a download.

**Comment by dan-alcantara-neeva** [comment]
Download looks cancelable to me:

<img src="https://user-images.githubusercontent.com/96092902/196292078-0f896a30-f1bc-4958-bf8d-999e0c733b71.jpg" width=500>

**Comment by Kokobe** [comment]
Oh I guess they meant via the `popup`

**Comment by Kokobe** [comment]
Closing because this feature seems pretty accessible from the swipe down menu.
