### ISSUE TITLE
Strict Mode content filtering blocks the user from logging into Google accounts

### ISSUE THREAD

**Issue by dan-alcantara-neeva** [neevaco/neeva-android#1064]
If you have Strict Mode and Content Filtering mode enabled, Google will consistently fail to let you log in.

https://user-images.githubusercontent.com/96092902/196619403-7e6a08e5-062f-44b6-bace-1b8ad9e841a1.mp4

**Comment by darinwf** [comment]
We should find out if the new updated filter lists solve this issue. Perhaps someone in the easylist community already resolved it for us. @Kokobe has a build w/ 106 that includes those changes. @Kokobe - can you test?

**Comment by chung-lai** [comment]
i just tried google.com and gmail on iOS. I was able to get to the password screens. How do you get to that google login?

**Comment by dan-alcantara-neeva** [comment]
Logged out of Google and just went to gmail.com on the app.

**Comment by Kokobe** [comment]
https://user-images.githubusercontent.com/20916043/196774781-32598613-cca6-420f-8d66-88e3307477df.mp4

It's still a problem on 106 @darinwf

**Comment by chung-lai** [comment]
It should be related to this: https://github.com/neevaco/neeva-ios/issues/3779

We may have to do the same work around on Android. We should not block the request if it's originated from the same domain. May require Chromium change? @darinwf

**Comment by Kokobe** [comment]
Fixed in chromium repo: https://github.com/neevaco/chromium/pull/19

Going to land it with #1063
