### ISSUE TITLE
Make URLBar textfield's floating action menu more easily show up

### ISSUE THREAD

**Issue by Kokobe** [neevaco/neeva-android#1102]
**Is your feature request related to a problem? Please describe.**
See: https://app.clickup.com/t/2zb5chz

**Describe the solution you'd like**
The floating action menu that has (Paste, Clickboard, and other options) should show up after tapping on the cursor instead of holding for 3 seconds (see the video in the click-up).

**Describe alternatives you've considered**
Alternative solution is to not change anything. Maybe holding for 3 seconds on a search bar is the norm, but apps like the Play Store or Chrome don't have that behavior. 

**Additional context**
For the textfield code see `URLBar.kt`

**Comment by dan-alcantara-neeva** [comment]
Closed because the member got back to us and discovered it was an OS issue.
