### ISSUE TITLE
Auth through accounts.google.com can leave the user stuck on about:blank

### ISSUE THREAD

**Issue by dan-alcantara-neeva** [neevaco/neeva-android#1116]
If a site tries to log on a user via Google in a new tab, the tab will close at the end of the flow but fail to send the user back to the opening tab.  This often happens during checkout flows, which causes the user to have to manually return to whatever tab they were on previously.

**Comment by dan-alcantara-neeva** [comment]
@Kokobe This is related to that problem I was asking about earlier for Content Filtering not working correctly with `auth.google.com`: even if I close the tab, the parent tab doesn't seem to get the correct signal it needs to complete login or checkout.

**Comment by Kokobe** [comment]
Does this happen only when content filtering is enabled?

**Comment by dan-alcantara-neeva** [comment]
When I tried it a few weeks ago, it seemed that way.  Will need to fix the first part of the bug before diving into the second, though.
