### ISSUE TITLE
Blocked Trackers Popup shows up on Neeva.com

### ISSUE THREAD

**Issue by Kokobe** [neevaco/neeva-android#1185]
After a login, this popup shows up for me:

https://user-images.githubusercontent.com/20916043/211223721-61ca9d3c-5bf3-4073-b5a5-a0c7ebcad590.mp4

This can be really misleading and users might think Neeva (a privacy app) is tracking them after they login.

**Comment by dan-alcantara-neeva** [comment]
That's weird, neeva.com should in the allowlist on install when the database is first initialized.

**Comment by Kokobe** [comment]
Yeah something in my new PR is causing this to happen @dan-alcantara-neeva 

Not sure what it is yet

**Comment by dan-alcantara-neeva** [comment]
Might be missing a call if you've changed how startup works.

**Comment by dan-alcantara-neeva** [comment]
FirstRunActivity does this:
```
        lifecycleScope.launch(dispatchers.io) {
            historyDatabase.hostInfoDao().initializeForFirstRun(neevaConstants)
        }
```

**Comment by Kokobe** [comment]
That was the problem! Thanks Dan 🙂
