### ISSUE TITLE
CookieCutter Dialog: Fix Box Size for Long Text (French)

### ISSUE THREAD

**Issue by Kokobe** [neevaco/neeva-android#917]
See: https://neevaco.slack.com/archives/C01QW9Z7P3P/p1660604095717059

![image](https://user-images.githubusercontent.com/20916043/186544323-5bf3309f-2b38-4a7f-b115-f31cefce369e.png)

**Comment by dan-alcantara-neeva** [comment]
Fixed this with https://github.com/neevaco/neeva-android/pull/963
