### ISSUE TITLE
Disable sending Feedback unless the user has typed something

### ISSUE THREAD

**Issue by dan-alcantara-neeva** [neevaco/neeva-android#989]
Been getting a lot of reports that have screenshots but no text, which aren't actionable.  We should disable the button for sending feedback until they've actually typed something in.

**Comment by darinwf** [comment]
We might also want to make it more obvious that the first input box is where you should type your feedback. The current placeholder text should maybe be gray instead (assuming that would be consistent with material design)? Also, perhaps we should focus the text box when showing the feedback form. (Although that might make it harder to see that there is an attached image, hmm.)

**Comment by dan-alcantara-neeva** [comment]
Looks like we're using the default placeholder defined by Material (because we don't override it).

```
OutlinedTextField(
    value = feedback.value,
    onValueChange = { newValue -> feedback.value = newValue },
    placeholder = {
        Text(stringResource(R.string.submit_feedback_textfield_placeholder))
    },
    modifier = Modifier
        .fillMaxWidth()
        .padding(horizontal = Dimensions.PADDING_LARGE)
)
```
